// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MNEE$Type } from "./MNEE";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MNEE"]: MNEE$Type;
    ["contracts/MNEE.sol:MNEE"]: MNEE$Type;
  }

  interface ContractTypesMap {
    ["MNEE"]: GetContractReturnType<MNEE$Type["abi"]>;
    ["contracts/MNEE.sol:MNEE"]: GetContractReturnType<MNEE$Type["abi"]>;
  }
}
