// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BountyEscrow$Type } from "./BountyEscrow";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BountyEscrow"]: BountyEscrow$Type;
    ["contracts/BountyEscrow.sol:BountyEscrow"]: BountyEscrow$Type;
  }

  interface ContractTypesMap {
    ["BountyEscrow"]: GetContractReturnType<BountyEscrow$Type["abi"]>;
    ["contracts/BountyEscrow.sol:BountyEscrow"]: GetContractReturnType<BountyEscrow$Type["abi"]>;
  }
}
