// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { GuildRegistry$Type } from "./GuildRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["GuildRegistry"]: GuildRegistry$Type;
    ["contracts/GuildRegistry.sol:GuildRegistry"]: GuildRegistry$Type;
  }

  interface ContractTypesMap {
    ["GuildRegistry"]: GetContractReturnType<GuildRegistry$Type["abi"]>;
    ["contracts/GuildRegistry.sol:GuildRegistry"]: GetContractReturnType<GuildRegistry$Type["abi"]>;
  }
}
