// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface LowLevelCall$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "LowLevelCall",
  "sourceName": "@openzeppelin/contracts/utils/LowLevelCall.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212206174b70f6681ffc0f830a6fb0c24c5d5d7715e6cef5ebaab049d79dc7c52647a64736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212206174b70f6681ffc0f830a6fb0c24c5d5d7715e6cef5ebaab049d79dc7c52647a64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "LowLevelCall",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LowLevelCall$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/LowLevelCall.sol:LowLevelCall",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LowLevelCall$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "LowLevelCall",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LowLevelCall$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/LowLevelCall.sol:LowLevelCall",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LowLevelCall$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "LowLevelCall",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LowLevelCall$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/LowLevelCall.sol:LowLevelCall",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LowLevelCall$Type["abi"]>>;
}
